---
# Configure Trunk Ports across the fabric
- name: Configure Distribution Switch Trunks
  cisco.ios.ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/0
        mode: trunk
        trunk:
          allowed_vlans: 10,99-100
          encapsulation: dot1q
          native_vlan: 100
      - name: GigabitEthernet0/1
        mode: trunk
        trunk:
          allowed_vlans: 10,99-100
          encapsulation: dot1q
          native_vlan: 100
    state: merged
  when: "'distribution_switches' in group_names"

- name: Configure Access Switch Trunks
  cisco.ios.ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/0
        mode: trunk
        trunk:
          allowed_vlans: 10,99-100
          encapsulation: dot1q
          native_vlan: 100
    state: merged
  when: "'access_switches' in group_names"
