[all:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_user=admin
ansible_password=admin
ansible_ssh_common_args='-o KexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa -o Ciphers=+aes128-cbc'

[distribution_switches]
SW-D-DEIE ansible_host=10.99.99.2
SW-D-DCEE ansible_host=10.99.99.3
SW-D-DMME ansible_host=10.99.99.4

[access_switches]
SW-A-DEIE ansible_host=10.99.99.10
SW-A-DCEE ansible_host=10.99.99.20
SW-A-DMME ansible_host=10.99.99.30
SW-A-DIS ansible_host=10.99.99.40

[switches:children]
distribution_switches
access_switches